name: "Terraform e Scripts CI/CD"

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: "Deploy Infra e Código"
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Config AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::321079154978:role/GitHubActionsDeployRole
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Sync scripts to S3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Syncing scripts to S3..."
          aws s3 sync ./scripts s3://lakehouse-portfolio-artifacts-datashi/scripts/ --delete
          